Repository np-guard/vmware-analyzer, pull requests merged in 2024-11, with the labels that each got.

#40 Update README.md
  README.md
Labels: size/XS

#42 Create dependabot.yaml
  .github/dependabot.yaml
Labels: size/S

#43 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: size/M

#48 Pagination
  pkg/collector/collectApi.go
Labels: size/M

#50 update go.mod
  go.mod
Labels: size/XS

#52 vm struct add uid
  pkg/collector/data/examples_generator.go
  pkg/collector/data/json/Example1.json
  pkg/collector/data/json/Example2.json
  pkg/model/config.go
  pkg/model/connectivity_test.go
  pkg/model/endpoints/vm.go
  pkg/model/parser.go
  pkg/model/parser_test.go
Labels: size/L

#55 Create anonymizer
  cmd/commands.go
  cmd/main_test.go
  pkg/anonymizer/anonymize.go
  pkg/anonymizer/anonymize_nsx.go
  pkg/anonymizer/anonymize_test.go
  pkg/anonymizer/anonymizer.go
  pkg/anonymizer/fieldAnonymization.go
  pkg/anonymizer/iterator.go
  pkg/anonymizer/reflectInterface.go
Labels: size/XL

#63 Example2 fix
  pkg/collector/data/examples.go
Labels: size/XS

#54 Traceflow
  cmd/commands.go
  pkg/collector/collectApi.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/data_model.go
  pkg/collector/resources_container_model.go
  pkg/collector/trace_flow.go
  pkg/collector/trace_flow_data_model.go
  pkg/model/generated/nsx_sdk.go
  schemas/schemas_downloader.py
  schemas/top_level_schemas.txt
Labels: size/XL
