Repository np-guard/vmware-analyzer, pull requests merged in 2024-12, with the labels that each got.

#58 Symbolic expr impl
  pkg/collector/collector.go
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/model/endpoints/vm.go
  pkg/model/synthesis/model.go
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/simplePath.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
Labels: size/L

#70 added code for multiple passes in presence of multiple higher priorit…
  pkg/model/synthesis/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
Labels: size/M

#73 69 small fixes
  pkg/symbolicexpr/README.md
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
Labels: size/L

#71 update parser: add vm tags
  pkg/model/endpoints/vm.go
  pkg/model/parser.go
Labels: size/S

#72 update example tests
  .github/workflows/go-test.yml
  cmd/main_test.go
  pkg/collector/data/examples.go
  pkg/collector/data/expected_output/Example3.txt
  pkg/collector/data/json/Example3.json
  pkg/model/analyzer_test.go
Labels: size/XXL

#75 Analyze missmatch - collect both services and service entries of a rule
  pkg/model/parser.go
Labels: size/M

#76 few analysis enhancements
  pkg/common/strings.go
  pkg/model/analyzer.go
  pkg/model/config.go
  pkg/model/connectivity.go
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/model/parser.go
Labels: size/L

#64 Vsphere collector
  .gitignore
  pkg/vsphrcoll/collectApi.go
  pkg/vsphrcoll/collector.go
  pkg/vsphrcoll/collector_test.go
Labels: size/L

#82 Syntesis policies struct re org
  pkg/synthesis/model.go
Labels: size/S

#79 Collect all mamber types
  cmd/main_test.go
  pkg/anonymizer/anonymize.go
  pkg/anonymizer/anonymize_nsx.go
  pkg/anonymizer/anonymizer.go
  pkg/collector/collector.go
  pkg/collector/data/examples_generator.go
  pkg/collector/data_model.go
  pkg/collector/trace_flow_data_model.go
  pkg/model/parser.go
Labels: size/L

#83 Add simple examples
  pkg/collector/data/examples.go
Labels: size/M

#84 Treat empty symbolic path
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
Labels: size/M

#81 collect Gateway firewall & rules
  pkg/collector/collector.go
  pkg/collector/data_model.go
  pkg/collector/resources_container_model.go
  pkg/model/generated/nsx_sdk.go
  schemas/top_level_schemas.txt
Labels: size/M

#80 Traceflow vs analyze
  .gitignore
  pkg/collector/collector_test.go
  pkg/collector/resources_container_model.go
  pkg/collector/trace_flow.go
  pkg/collector/trace_flow_data_model.go
  pkg/model/analyzer.go
  pkg/model/verify_trace_flow.go
  pkg/model/verify_trace_flow_test.go
Labels: size/XL

#90 collect the server from environment variables
  cmd/main_test.go
  pkg/collector/collector_test.go
  pkg/model/verify_trace_flow_test.go
  pkg/vsphrcoll/collector_test.go
Labels: size/M

#92 add example to unit tests
  pkg/collector/data/examples.go
  pkg/collector/data/expected_output/ExampleDumbeldore.txt
  pkg/collector/data/json/ExampleDumbeldore.json
  pkg/model/analyzer_test.go
Labels: size/XXL

#95 Synthesis test
  pkg/synthesis/model.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDumbeldore.txt
Labels: size/M

#94 Synthesis pre processing
  pkg/collector/data_model.go
  pkg/model/config.go
  pkg/model/connectivity_test.go
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/model/parser.go
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/model.go
  pkg/synthesis/symbolicPolicy.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDumbeldore.txt
Labels: size/XL

#100 Adding connection to symblic presentation, with relevant optimzations
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDumbeldore.txt
Labels: size/L

#105 Policy conversion
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_PreProcessing.txt
Labels: size/L

#107 104 generate test
  pkg/synthesis/synthesis_test.go
Labels: size/M

#108 106 add synthesis tests
  pkg/collector/data/examples.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_PreProcessing.txt
Labels: size/L
