Repository np-guard/vmware-analyzer, pull requests merged in 2025-04, with the labels that each got.

#385 extend lint cmd - redundant rules report
  README.md
  pkg/analyzer/analyzer_test.go
  pkg/analyzer/explanation_test.go
  pkg/collector/dfwCategory.go
  pkg/configuration/config.go
  pkg/configuration/dfw/category.go
  pkg/configuration/dfw/dfw.go
  pkg/configuration/dfw/rule.go
  pkg/configuration/lint/lint.go
  pkg/configuration/redundant_analysis_test.go
  pkg/data/examples_generator.go
  pkg/data/examples_test.go
  pkg/data/json/no_redundant_rules.json
  pkg/data/json/one_duplicated_rule.json
  pkg/data/json/one_duplicated_rule_one_direction_only.json
  pkg/data/json/one_redundant_covered_by_2_rules.json
  pkg/data/json/one_redundant_rule_containment_in_higher_prio_rule.json
  pkg/runner/runner.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#356 filter collected resource by VMs
  internal/common/strings.go
  pkg/analyzer/analyzer.go
  pkg/cli/args.go
  pkg/cli/generate.go
  pkg/configuration/config.go
  pkg/configuration/filter_resources.go
  pkg/configuration/parser.go
  pkg/configuration/redundant_analysis_test.go
  pkg/configuration/topology.go
  pkg/data/examples.go
  pkg/data/examples_test.go
  pkg/runner/runner.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegmentsFiltered_NoHint_Filtered.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsFiltered_Filtered.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsFiltered_Filtered/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsFiltered_Filtered/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/Example1dExternalWithSegmentsFiltered_NoHint_Filtered.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsFiltered_Filtered.txt
Labels: size/XL

#398 fixing Traceflow to work on manager api
  internal/common/netset.go
  pkg/analyzer/verify_trace_flow.go
  pkg/analyzer/verify_trace_flow_test.go
  pkg/collector/collectApi.go
  pkg/collector/collector_test.go
  pkg/collector/trace_flow.go
  pkg/collector/trace_flow_data_model.go
  pkg/configuration/topology.go
  pkg/synthesis/kubectl_test.go
Labels: size/L

#392 implement Internal ip resources
  pkg/analyzer/connectivity/connectivity.go
  pkg/configuration/config.go
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/data/examples.go
  pkg/data/json/ExampleInternalWithInterDenyAllow.json
  pkg/data/json/ExampleInternalWithInterDenyAllowMixedSegments.json
  pkg/data/json/ExampleInternalWithInterDenyAllowWithSegments.json
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/symbolicexpr/internalIPTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/segmentTerm.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllowMixedSegments.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllowWithSegments.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllow/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllow/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllowMixedSegments.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllowWithSegments.txt
Labels: size/XXL

#400 391 tautology and externals
  pkg/data/examples.go
  pkg/data/json/ExampleExternalWithTautology.json
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/symbolicexpr_IPBlock_test.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalWithTautology.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithTautology/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithTautology/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalWithTautology.txt
Labels: size/XXL

#399 390 tautology and internals
  pkg/data/examples.go
  pkg/data/json/ExampleExternalWithTautology.json
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/symbolicexpr/allExternalI.go
  pkg/synthesis/symbolicexpr/allGroup.go
  pkg/synthesis/symbolicexpr/anyInternalResource.go
  pkg/synthesis/symbolicexpr/atomicGeneral.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/contradiction.go
  pkg/synthesis/symbolicexpr/externalIPTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/noGroup.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/symbolicexpr/symbolicexpr_GroupTag_test.go
  pkg/synthesis/symbolicexpr/symbolicexpr_IPBlock_test.go
  pkg/synthesis/symbolicexpr/tautology.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalWithTautology.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllowMixedSegments.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllowWithSegments.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithTautology/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithTautology/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllow/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalWithTautology.txt
Labels: size/XXL

#404 403 receivers inconsistency
  pkg/synthesis/symbolicexpr/allExternalI.go
  pkg/synthesis/symbolicexpr/allGroup.go
  pkg/synthesis/symbolicexpr/contradiction.go
  pkg/synthesis/symbolicexpr/externalIPTerm.go
  pkg/synthesis/symbolicexpr/groupAtomicTerm.go
  pkg/synthesis/symbolicexpr/internalIPTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/noGroup.go
  pkg/synthesis/symbolicexpr/segmentTerm.go
  pkg/synthesis/symbolicexpr/tagTerm.go
  pkg/synthesis/symbolicexpr/tautology.go
Labels: size/M

#406 fix printed rule scope + add makefile target test-fail-fast
  Makefile
  pkg/configuration/dfw/rule_str.go
  pkg/configuration/parser.go
  scripts/tests_fail_fast.sh
Labels: size/S

#408 add rules action to explain report + add example test
  pkg/analyzer/analyzer_test.go
  pkg/analyzer/category_analysis.go
  pkg/analyzer/connectivity/detailed_connection.go
  pkg/analyzer/tests_expected_output/ExampleAppWithGroupsAdditionalDropRule.txt
  pkg/data/examples.go
  pkg/data/json/ExampleAppWithGroupsAdditionalDropRule.json
Labels: size/XXL

#409 add test-fail-fast to ci flow
  .github/workflows/test-fail-fast.yml
  scripts/tests_fail_fast.sh
Labels: size/M

#407 Support allexternal synthesis
  pkg/configuration/topology/ip_blocks.go
  pkg/data/examples.go
  pkg/data/json/ExampleInternalWithInterDenyAllowMixedSegments.json
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/symbolicexpr/allExternalI.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/externalIPTerm.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllow/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllowMixedSegments.txt
Labels: size/XL

#412 Create namespaces resource
  pkg/configuration/topology.go
  pkg/data/examples_generator.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sNamspace.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/namespaces.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegmentsFiltered_NoHint_Filtered/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/namespaces.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndCondsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrCondsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopesAbstract/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllow/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/namespaces.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowMixedSegments/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/namespaces.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleInternalWithInterDenyAllowWithSegments/policies.yaml
Labels: size/XXL
