Repository np-guard/vmware-analyzer, pull requests merged in 2025-01, with the labels that each got.

#112 fixed bug and implied tests
  pkg/symbolicexpr/atomic.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstract.txt
Labels: size/S

#113 106 remove implied paths optimization
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstract.txt
Labels: size/L

#109 Collect vm tags and groups for synthesis
  pkg/collector/data_model.go
  pkg/model/endpoints/vm.go
  pkg/model/parser.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#117 106 hint disjoint groups
  pkg/collector/data/examples.go
  pkg/collector/data/examples_generator.go
  pkg/symbolicexpr/README.md
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_ConvertToAbstractNoHint.txt
Labels: size/XL

#120 118 decouple synthesis test
  pkg/collector/data/examples.go
  pkg/collector/data/examples_generator.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
Labels: size/XL

#121 Nsx demo example abstract model
  pkg/symbolicexpr/symbolicPath.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_PreProcessing.txt
Labels: size/XL

#123 analysis with rules explanations + traceflow test enhancements
  cmd/commands.go
  pkg/collector/collector_test.go
  pkg/collector/data/examples.go
  pkg/collector/data/examples_generator.go
  pkg/collector/data/expected_output/Example1.txt
  pkg/collector/data/expected_output/Example2.txt
  pkg/collector/data/expected_output/Example3.txt
  pkg/collector/data/expected_output/ExampleDumbeldore.txt
  pkg/collector/data/json/Example1a.json
  pkg/collector/data/json/Example1b.json
  pkg/collector/data/json/basic_jump_to_app_test.json
  pkg/collector/data/json/basic_jump_to_app_test_2.json
  pkg/collector/data/json/default_allow_first.json
  pkg/collector/data/json/default_deny_first.json
  pkg/collector/data/json/direction_in_and_out_separate_rules.json
  pkg/collector/data/json/direction_in_separate_rule_res_is_allow.json
  pkg/collector/data/json/direction_in_separate_rule_res_is_drop.json
  pkg/collector/data/json/one_allow_and_default_deny.json
  pkg/collector/data/json/one_allow_rule_multiple_services.json
  pkg/collector/data/json/one_allow_rule_multiple_services_partial_redundant.json
  pkg/collector/data/json/one_deny_and_default_allow.json
  pkg/collector/data/json/two_allow_default_deny.json
  pkg/collector/data/json/two_allow_rules.json
  pkg/collector/topology_tree.go
  pkg/collector/trace_flow.go
  pkg/common/errors.go
  pkg/common/graphs.go
  pkg/common/output.go
  pkg/common/strings.go
  pkg/model/analyzer.go
  pkg/model/analyzer_test.go
  pkg/model/config.go
  pkg/model/connectivity.go
  pkg/model/connectivity/connectivity.go
  pkg/model/connectivity/detailed_connection.go
  pkg/model/connectivity/disjoint_explain.go
  pkg/model/connectivity/explain.go
  pkg/model/connectivity/explain_test.go
  pkg/model/connectivity/output.go
  pkg/model/connectivity_test.go
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/model/explanation_test.go
  pkg/model/output.go
  pkg/model/verify_trace_flow.go
  pkg/model/verify_trace_flow_test.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
  pkg/vsphrcoll/collector_test.go
Labels: size/XXL

#125 Update documentation
  README.md
  docs/nsx_support.md
  pkg/collector/data_model.go
Labels: size/M

#126 update groups parsing, ignore vms without groups
  pkg/common/strings.go
  pkg/model/config.go
  pkg/model/endpoints/vm.go
  pkg/model/parser.go
  pkg/synthesis/synthesis.go
Labels: size/M

#127 create k8s resources
  go.mod
  go.sum
  pkg/common/system.go
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/model.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_PreProcessing.txt
Labels: size/XL

#128 Synthesis cli
  cmd/commands.go
  cmd/main_test.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/M

#133 fixing some comments about synthesis
  pkg/symbolicexpr/atomic.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/synthesis_test.go
Labels: size/S

#138 137 abstract admin np
  cmd/commands.go
  pkg/model/dfw/category.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/ExampleHogwarts_ConvertToAbstract.txt_Application
  pkg/synthesis/tests_expected_output/ExampleHogwarts_PreProcessing_Application.txt
Labels: size/L

#136 handling Rule.destinationsExcluded
  .gitignore
  docs/nsx_support.md
  pkg/collector/data/examples.go
  pkg/collector/data/examples_generator.go
  pkg/collector/data/expected_output/ExampleExclude.txt
  pkg/collector/data/json/ExampleExclude.json
  pkg/common/system.go
  pkg/model/analyzer_test.go
  pkg/model/dfw/rule.go
  pkg/model/explanation_test.go
  pkg/model/parser.go
Labels: size/XXL

#143 converting abstract model to nsx rules - validation of transformatioin
  pkg/collector/data/examples_generator.go
  pkg/model/endpoints/vm.go
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#146 add Dockerfile + small makefile update
  Dockerfile
  Makefile
Labels: size/S

#150 Abstract deny rule to nsx rule
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/synthesis_test.go
Labels: size/M

#152 148 example generate expr
  pkg/collector/data/examples.go
  pkg/collector/data/examples_generator.go
  pkg/collector/data_model.go
  pkg/model/explanation_test.go
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
Labels: size/XL

#149 Creating admin network policies
  README.md
  cmd/commands.go
  cmd/main_test.go
  pkg/model/dfw/category.go
  pkg/model/dfw/rule.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/k8sPorts.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/XL

#157 Remove netpol analyzer dependencies + netpol expected results
  go.mod
  go.sum
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_true_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_true_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_true_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_true_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_true_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_true_0/policies.yaml
Labels: size/XXL

#160 Few analysis/log/output improvements
  cmd/main_test.go
  pkg/collector/data/expected_output/Example1.txt
  pkg/collector/data/expected_output/Example2.txt
  pkg/collector/data/expected_output/Example3.txt
  pkg/collector/data/expected_output/ExampleDumbeldore.txt
  pkg/collector/data/expected_output/ExampleExclude.txt
  pkg/collector/data_model.go
  pkg/collector/resources_container_model.go
  pkg/common/graphs.go
  pkg/common/strings.go
  pkg/model/config.go
  pkg/model/connectivity/output.go
  pkg/model/connectivity_test.go
  pkg/model/dfw/category.go
  pkg/model/dfw/dfw.go
  pkg/model/dfw/rule.go
  pkg/model/endpoints/vm.go
  pkg/model/parser.go
  pkg/synthesis/createNSXPolicies.go
Labels: size/XL

#161 Add default deny network policy
  pkg/collector/data/examples.go
  pkg/collector/data/json/Example1c.json
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
  pkg/synthesis/tests_expected_output/Example1c_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/Example1c_PreProcessing.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_true_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_true_0/policies.yaml
Labels: size/XXL

#163 update dockerfile - use: from scratch
  Dockerfile
Labels: size/XS

#162 Group term
  pkg/symbolicexpr/atomic.go
  pkg/symbolicexpr/atomicGeneral.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/groupTerm.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/createNSXPolicies.go
Labels: size/XL

#166 Tag atomic term
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/groupTerm.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/synthesis.go
Labels: size/L

#167 update documentation and makefile
  Dockerfile
  Makefile
  README.md
  cmd/commands.go
Labels: size/L

#170 cli updates
  README.md
  cmd/commands.go
  cmd/main_test.go
  pkg/collector/collector_test.go
  pkg/collector/nsx_conn.go
  pkg/collector/resources_container_model.go
  pkg/common/errors.go
  pkg/common/graphs.go
  pkg/common/output.go
  pkg/common/strings.go
  pkg/model/analyzer.go
  pkg/model/config.go
  pkg/model/connectivity/output.go
  pkg/model/dfw/dfw.go
  pkg/model/explanation_test.go
  pkg/model/verify_trace_flow.go
  pkg/model/verify_trace_flow_test.go
  pkg/synthesis/synthesis_test.go
Labels: size/XL

#169 one In/outbound list - to set proirity in right order
  pkg/model/dfw/category.go
  pkg/model/dfw/rule.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_true_0/policies.yaml
Labels: size/XL

#173 Update log
  pkg/model/dfw/dfw.go
Labels: size/XS
