Repository np-guard/vmware-analyzer, pull requests merged in 2025-02, with the labels that each got.

#177 cli validate output format values
  cmd/commands.go
  cmd/enum_flags.go
  cmd/main_test.go
  pkg/model/connectivity/output.go
Labels: size/M

#185 convert connections to nsx services entries
  pkg/collector/data/examples_generator.go
  pkg/collector/data_model.go
  pkg/common/errors.go
  pkg/common/system.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/k8sPorts.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#186 1. compact vm slices 2. store configuration str for test
  pkg/model/analyzer.go
  pkg/model/endpoints/vm.go
  pkg/model/parser.go
  pkg/synthesis/synthesis_test.go
Labels: size/M

#193 183 remove subset optimization bug
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
Labels: size/M

#195 added document
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
Labels: size/XS

#189 synthesis - support tag expressions
  pkg/collector/data/examples_generator.go
  pkg/symbolicexpr/groupTerm.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
  pkg/synthesis/tests_expected_output/ExampleExprAndConds_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprAndConds_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprOrConds_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprOrConds_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprSingleScope_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprSingleScope_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprTwoScopes_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprTwoScopes_PreProcessing.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes_false_0/policies.yaml
Labels: size/XXL

#198 Create groups from tags
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope_false_0/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes_false_0/pods.yaml
Labels: size/M

#201 67 path string
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/synthesis/tests_expected_output/Example1c_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/Example1c_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleDenyPassSimple_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleDumbeldore_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprAndConds_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprAndConds_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprOrConds_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprOrConds_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprSingleScope_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprSingleScope_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleExprTwoScopes_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleExprTwoScopes_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHintsDisjoint_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsNoDumbledore_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleHogwartsSimpler_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_ConvertToAbstract.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_ConvertToAbstract.txt_Application
  pkg/synthesis/tests_expected_output/ExampleHogwarts_PreProcessing.txt
  pkg/synthesis/tests_expected_output/ExampleHogwarts_PreProcessing_Application.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_ConvertToAbstractNoHint.txt
  pkg/synthesis/tests_expected_output/ExampleTwoDeniesSimple_PreProcessing.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_true_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_0/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts_false_4/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_true_0/policies.yaml
Labels: size/XL

#210 update gitignore
  .gitignore
Labels: size/XS

#212 Cli hints
  README.md
  cmd/commands.go
  cmd/main_test.go
Labels: size/S

#209 print abstract policy to log
  pkg/symbolicexpr/groupTerm.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/S

#216 Enhancements for network policy generation
  cmd/commands.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_NoHint/policies.yaml
Labels: size/XL

#219 add make-release.yaml
  .github/workflows/make-release.yaml
Labels: size/M

#204 190 vm groups from expr
  pkg/collector/data/examples_generator.go
  pkg/synthesis/tests/examples.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/pods.yaml
Labels: size/XL

#220 synthesizeAdmin flag as an input to synthesis, instead of category
  cmd/commands.go
  pkg/collector/dfwCategory.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#222 Get default nsx rule id, to srore at the default k8s policy
  pkg/model/config.go
  pkg/model/dfw/rule.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_NoHint/policies.yaml
Labels: size/M

#221 Fix dfw output
  pkg/collector/data_model.go
  pkg/common/strings.go
  pkg/model/dfw/rule.go
  pkg/symbolicexpr/atomicGeneral.go
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/groupTerm.go
  pkg/symbolicexpr/model.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/symbolicexpr_test.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/preProcessing.go
Labels: size/L

#225 fix release workflow
  .github/workflows/make-release.yaml
Labels: size/XS

#223 213 wrong log
  pkg/symbolicexpr/groupTerm.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/preProcessing.go
Labels: size/M

#224 Support log file cli
  README.md
  cmd/commands.go
  cmd/main.go
  cmd/main_test.go
  pkg/collector/collector_test.go
  pkg/logging/logger.go
  pkg/model/analyzer_test.go
  pkg/model/verify_trace_flow_test.go
  pkg/synthesis/synthesis_test.go
Labels: size/M

#228 206 msgs wording
  pkg/collector/data_model.go
  pkg/symbolicexpr/tagTerm.go
  pkg/synthesis/synthesis.go
Labels: size/M

#239 168 enrich examples
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprAndConds.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprOrConds.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwarts.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimpler_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprAndConds.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprOrConds.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwarts.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsSimpler_NoHint.txt
Labels: size/XL

#249 Correct rules sort
  pkg/model/dfw/category.go
  pkg/model/dfw/rule.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/policies.yaml
Labels: size/L

#253 191 optimize global scope
  pkg/symbolicexpr/conjunction.go
  pkg/symbolicexpr/symbolicPath.go
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprOrConds.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/policies.yaml
Labels: size/L

#258 fix access to categories
  pkg/synthesis/createNSXPolicies.go
Labels: size/S

#256 250 admin policy abstract model test
  pkg/synthesis/model.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1c_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleDenyPassSimple.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleDenyPassSimple_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleDumbeldore_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprAndConds.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprOrConds.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprSingleScope.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprTwoScopes.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHintsDisjoint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHintsDisjoint_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwarts.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsNoDumbledore.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsNoDumbledore_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimpler.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimpler_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwarts_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleTwoDeniesSimple.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleTwoDeniesSimple_NoHint.txt
Labels: size/L

#261 260 no nsx
  pkg/synthesis/allowOnlyConversion.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1c_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleDenyPassSimple_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleDumbeldore_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprAndConds.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprAndCondsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprOrConds.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprOrCondsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprSingleScope.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprTwoScopes.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHintsDisjoint_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwarts.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsNoDumbledore.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimpler_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleTwoDeniesSimple_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/Example1c_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleDenyPassSimple_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleDumbeldore_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprAndConds.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprAndCondsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprOrConds.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprOrCondsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprSingleScope.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprTwoScopes.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHintsDisjoint_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwarts.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsNoDumbledore.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsSimpler_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleTwoDeniesSimple_NoHint.txt
Labels: size/XL

#262 creating dns admin policy
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/k8sPorts.go
  pkg/synthesis/tests_expected_output/k8s_resources/Example1c_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDenyPassSimple_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndCondsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprAndCondsAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrConds/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrCondsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprOrCondsAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopes/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHintsDisjoint_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwarts/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsNoDumbledore/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_NoHint/policies.yaml
Labels: size/XXL

#266 make warning msg clearer
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
Labels: size/S

#264 dynamic connectivity tests for k8s env
  internal/common/slices.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/verify_trace_flow.go
  pkg/logging/logger.go
  pkg/synthesis/kubectl_test.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#272 compare netpol connectivityvto vmwere connectivity
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/kubectl_test.go
  pkg/synthesis/synthesis_test.go
Labels: size/M, testing

#267 Synthesis rules with src/dst with no VMs
  pkg/analyzer/config.go
  pkg/analyzer/dfw/category.go
  pkg/analyzer/dfw/category_analysis.go
  pkg/analyzer/dfw/dfw.go
  pkg/analyzer/dfw/rule.go
  pkg/analyzer/dfw/rule_str.go
  pkg/analyzer/parser.go
  pkg/synthesis/model.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests/examples.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleDumbeldore_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprSingleScope.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExprTwoScopesAbstract.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleTwoDeniesSimple_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleDumbeldore_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprSingleScope/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopesAbstract/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExprTwoScopesAbstract/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleTwoDeniesSimple_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleExprTwoScopesAbstract.txt
Labels: size/XXL, v0.1.1

#273 Start topology parsing
  pkg/analyzer/parser.go
  pkg/analyzer/topology.go
Labels: size/M

#274 Endpoint Interface
  internal/common/slices.go
  pkg/analyzer/config.go
  pkg/analyzer/connectivity/connectivity.go
  pkg/analyzer/connectivity/explain_test.go
  pkg/analyzer/dfw/category.go
  pkg/analyzer/dfw/category_analysis.go
  pkg/analyzer/dfw/dfw.go
  pkg/analyzer/dfw/rule.go
  pkg/analyzer/dfw/rule_str.go
  pkg/analyzer/endpoints/endpoint.go
  pkg/analyzer/endpoints/vm.go
  pkg/analyzer/parser.go
  pkg/analyzer/topology.go
  pkg/analyzer/verify_trace_flow.go
  pkg/analyzer/verify_trace_flow_test.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/model.go
Labels: size/L

#275 Add example with ip blocks
  pkg/analyzer/analyzer_test/analyzer_test.go
  pkg/data/examples.go
  pkg/data/expected_output/ExampleExternal.txt
  pkg/data/json/Example1External.json
Labels: size/XXL

#278 268 refactor tests and tests results location
  README.md
  pkg/analyzer/analyzer_test.go
  pkg/analyzer/explanation_test.go
  pkg/analyzer/tests_expected_output/Example1.txt
  pkg/analyzer/tests_expected_output/Example1d.txt
  pkg/analyzer/tests_expected_output/Example2.txt
  pkg/analyzer/tests_expected_output/Example3.txt
  pkg/analyzer/tests_expected_output/ExampleDumbeldore.txt
  pkg/analyzer/tests_expected_output/ExampleExclude.txt
  pkg/analyzer/tests_expected_output/ExampleExternal.txt
  pkg/analyzer/tests_expected_output/ex2Filter1.svg
  pkg/data/actual_output/Example1.txt
  pkg/data/actual_output/Example1d.txt
  pkg/data/actual_output/Example2.txt
  pkg/data/actual_output/Example3.txt
  pkg/data/actual_output/ExampleDumbeldore.txt
  pkg/data/actual_output/ExampleExclude.txt
Labels: size/M
