Repository np-guard/vmware-analyzer, pull requests merged in 2025-03, with the labels that each got.

#287 Refactor config and analyzer
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  pkg/analyzer/category_analysis.go
  pkg/analyzer/connections_and_rules.go
  pkg/analyzer/connectivity/connectivity.go
  pkg/analyzer/connectivity/explain_test.go
  pkg/analyzer/dfw_analysis.go
  pkg/analyzer/explanation_test.go
  pkg/analyzer/verify_trace_flow.go
  pkg/analyzer/verify_trace_flow_test.go
  pkg/configuration/config.go
  pkg/configuration/dfw/category.go
  pkg/configuration/dfw/dfw.go
  pkg/configuration/dfw/rule.go
  pkg/configuration/dfw/rule_str.go
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/configuration/topology/endpoint.go
  pkg/configuration/topology/ip_blocks.go
  pkg/configuration/topology/vm.go
  pkg/runner/runner.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/kubectl_test.go
  pkg/synthesis/model.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/XL

#288 add operator-build automation for ci
  .github/workflows/operator-build.yml
  Makefile
Labels: size/S

#292 Analyze rule block to connectivity
  pkg/analyzer/analyzer.go
  pkg/analyzer/tests_expected_output/ExampleExternal.txt
  pkg/configuration/config.go
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/configuration/topology/external_ip.go
  pkg/configuration/topology/ip_blocks.go
  pkg/data/examples.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1External_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1External_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1External_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/Example1External_NoHint.txt
Labels: size/L

#294 add insecureSkipVerify flag
  cmd/commands.go
  operator/internal/controller/nsxmigration_controller.go
  pkg/analyzer/verify_trace_flow_test.go
  pkg/collector/collectApi.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/nsx_conn.go
  pkg/runner/runner.go
  pkg/synthesis/synthesis_test.go
Labels: size/L

#295 update vsphrcoll: add insecureSkipVerify arg
  pkg/internal/vsphrcoll/collectApi.go
  pkg/internal/vsphrcoll/collector.go
  pkg/internal/vsphrcoll/collector_test.go
Labels: size/S

#293 operator output as configmaps
  Makefile
  cmd/commands.go
  internal/common/graphs.go
  internal/common/json.go
  operator/Dockerfile
  operator/internal/controller/nsxmigration_controller.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/analyzer_test.go
  pkg/analyzer/explanation_test.go
  pkg/analyzer/verify_trace_flow.go
  pkg/collector/resources_container_model.go
  pkg/collector/trace_flow.go
  pkg/configuration/config.go
  pkg/configuration/config_json.go
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/configuration/topology/endpoint.go
  pkg/configuration/topology/external_ip.go
  pkg/configuration/topology/segment.go
  pkg/configuration/topology/vm.go
  pkg/internal/vsphrcoll/collector.go
  pkg/runner/observations.go
  pkg/runner/runner.go
  pkg/synthesis/synthesis.go
  pkg/synthesis/synthesis_test.go
Labels: size/XL

#297 Handle internal IPs in rule block
  pkg/analyzer/analyzer_test.go
  pkg/analyzer/tests_expected_output/Example1dExternalWithSegments.txt
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/data/examples.go
  pkg/data/examples_generator.go
  pkg/data/json/Example1dExternalWithSegments.json
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/Example1dExternalWithSegments_NoHint.txt
Labels: size/XXL

#301 small update
  README.md
  operator/scripts/rebuild.sh
Labels: size/XS

#302 Tmp fix for ip6 addresses + fix not k8s legal labels
  pkg/configuration/topology.go
  pkg/synthesis/createK8sResources.go
  pkg/synthesis/k8sPolicies.go
Labels: size/M

#306 291 atomic ip block
  pkg/configuration/topology/external_ip.go
  pkg/configuration/topology/ip_blocks.go
  pkg/synthesis/symbolicexpr/atomicGeneral.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/contradiction.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/symbolicexpr/symbolicexpr_GroupTag_test.go
  pkg/synthesis/symbolicexpr/symbolicexpr_IPBlock_test.go
  pkg/synthesis/symbolicexpr/tagTerm.go
  pkg/synthesis/symbolicexpr/tautology.go
Labels: size/XL

#317 315 ip block term preprocessing
  pkg/configuration/dfw/rule.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1External_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1External_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/Example1External_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/Example1dExternalWithSegments_NoHint.txt
Labels: size/L

#312 running user resorcse file as sub tests
  .gitignore
  pkg/data/examples_generator.go
  pkg/data/json/Example1External.json
  pkg/data/json/Example1dExternalWithSegments.json
  pkg/synthesis/synthesis_test.go
Labels: size/L

#309 adding example with 0.0.0.0/0 + fix rules for external endpoints
  pkg/analyzer/analyzer.go
  pkg/analyzer/connectivity/connectivity.go
  pkg/analyzer/connectivity/explain_test.go
  pkg/analyzer/dfw_analysis.go
  pkg/analyzer/tests_expected_output/Example1dExternalWithSegments.txt
  pkg/configuration/parser.go
  pkg/configuration/topology/endpoint.go
  pkg/configuration/topology/external_ip.go
  pkg/configuration/topology/vm.go
  pkg/data/examples.go
  pkg/data/examples_generator.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/Example1dExternalWithSegments_NoHint.txt
Labels: size/M

#322 319 ip block examples
  pkg/data/examples.go
  pkg/data/json/ExampleExternalSimpleWithInterlDenyAllow.json
  pkg/data/json/ExampleExternalWithDenySimple.json
  pkg/data/json/ExampleHogwartsOut.json
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalSimpleWithInterlDenyAllow_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalWithDenySimple_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsExternal.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllow_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllow_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithDenySimple_NoHint/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithDenySimple_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternal/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternal/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalSimpleWithInterlDenyAllow_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalWithDenySimple_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsExternal.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled.txt
Labels: size/XXL

#324 307 synthesis scope
  pkg/configuration/dfw/category.go
  pkg/configuration/dfw/dfw.go
  pkg/configuration/dfw/rule.go
  pkg/configuration/parser.go
  pkg/synthesis/preProcessing.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
Labels: size/M

#329 Why default rule missing
  pkg/analyzer/dfw_analysis.go
  pkg/configuration/topology.go
  pkg/data/examples.go
  pkg/logging/logger.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/pods.yaml
Labels: size/M

#328 tag and group terms disjoint to external IP
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
  pkg/synthesis/symbolicexpr/tagTerm.go
Labels: size/S

#331 Bundle rule inout
  pkg/analyzer/category_analysis.go
  pkg/configuration/dfw/category.go
  pkg/configuration/dfw/dfw.go
  pkg/configuration/dfw/rule.go
  pkg/configuration/dfw/rule_str.go
  pkg/configuration/parser.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
Labels: size/L

#334 fix Json error - must have resource type for expressions
  pkg/data/examples_generator.go
  pkg/data/json/ExampleExprAndConds.json
  pkg/data/json/ExampleExprSingleScope.json
  pkg/data/json/ExampleExprTwoScopes.json
  pkg/data/json/ExampleOrSimple.json
Labels: size/XL

#335 Complementary() member func for IPBlock from netset
  go.mod
  go.sum
  operator/go.mod
  operator/go.sum
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
Labels: size/S

#337 Bundle leftover
  pkg/configuration/dfw/category.go
  pkg/configuration/dfw/dfw.go
  pkg/configuration/dfw/rule.go
  pkg/configuration/parser.go
Labels: size/M

#327 synthesys abstract Ipblocks to k8s netpol
  pkg/analyzer/dfw_analysis.go
  pkg/configuration/config.go
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/data/examples.go
  pkg/data/json/ExampleExternalSimpleWithInterlDenyAllow.json
  pkg/data/json/ExampleHogwartsExternal.json
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/symbolicexpr/atomicGeneral.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/contradiction.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/tagTerm.go
  pkg/synthesis/symbolicexpr/tautology.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleExternalSimpleWithInterlDenyAllow_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1External_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled/adminPolicies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalSimpleWithInterlDenyAllow_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleExternalWithDenySimple_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternal/policies.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalSimpleWithInterlDenyAllowAdmin_NoHint_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleExternalSimpleWithInterlDenyAllow_NoHint.txt
Labels: size/XXL

#336 seperate rule block to internal and external interface
  pkg/configuration/topology.go
  pkg/configuration/topology/ip_blocks.go
Labels: size/S

#340 Create ipblock nsx resources
  pkg/data/examples_generator.go
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/synthesis_test.go
Labels: size/S

#333 316 group all diff tautology
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/symbolicexpr/allGroup.go
  pkg/synthesis/symbolicexpr/atomicGeneral.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/contradiction.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/noGroup.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/symbolicexpr/symbolicexpr_GroupTag_test.go
  pkg/synthesis/symbolicexpr/symbolicexpr_IPBlock_test.go
  pkg/synthesis/symbolicexpr/tagTerm.go
  pkg/synthesis/symbolicexpr/tautology.go
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsExternalAdmin_AdminPoliciesEnabled/adminPolicies.yaml
Labels: size/XL

#347 scope bug fix
  pkg/configuration/dfw/rule.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
Labels: size/S

#346 345 ip term external only
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/symbolicexpr/ipBlockTerm.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/Example1dExternalWithSegments_NoHint.txt
Labels: size/M

#349 348 groups for internal
  pkg/synthesis/symbolicexpr/abstractGroupTerm.go
  pkg/synthesis/symbolicexpr/groupAtomicTerm.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/internalIPTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/symbolicexpr_GroupTag_test.go
Labels: size/L

#352 Redundancy analysis and lint cli
  README.md
  cmd/commands.go
  cmd/main.go
  cmd/main_test.go
  docs/synthesis.md
  go.mod
  internal/common/trafficset.go
  pkg/analyzer/analyzer.go
  pkg/analyzer/category_analysis.go
  pkg/analyzer/connectivity/detailed_connection.go
  pkg/analyzer/connectivity/explain.go
  pkg/analyzer/connectivity/output.go
  pkg/analyzer/dfw_analysis.go
  pkg/cli/analyze.go
  pkg/cli/args.go
  pkg/cli/collect.go
  pkg/cli/enum_flags.go
  pkg/cli/generate.go
  pkg/cli/lint.go
  pkg/cli/root.go
  pkg/cli/run.go
  pkg/collector/nsx_conn.go
  pkg/configuration/config.go
  pkg/configuration/dfw/category.go
  pkg/configuration/dfw/dfw.go
  pkg/configuration/parser.go
  pkg/configuration/redundant_analysis_test.go
  pkg/configuration/topology.go
  pkg/data/examples.go
  pkg/data/json/Example1aRedundantRuleIn.json
  pkg/data/json/Example1aRedundantRuleInOut.json
  pkg/data/json/Example1aRedundantRuleOut.json
  pkg/data/json/Example1aRedundantRuleOutInSeparated.json
  pkg/data/json/no_redundant_rules.json
  pkg/data/json/one_duplicated_rule.json
  pkg/data/json/one_duplicated_rule_one_direction_only.json
  pkg/data/json/one_redundant_covered_by_2_rules.json
  pkg/data/json/one_redundant_rule_containment_in_higher_prio_rule.json
  pkg/runner/runner.go
Labels: size/XXL

#355 move trafficset to models + update models version in go.mod + delete …
  go.mod
  go.sum
  internal/common/trafficset.go
  operator/go.mod
  operator/go.sum
  pkg/analyzer/analyzer.go
  pkg/analyzer/category_analysis.go
  pkg/configuration/dfw/category.go
Labels: size/L

#357 348 internal ip term
  pkg/synthesis/createNSXPolicies.go
  pkg/synthesis/k8sPolicies.go
  pkg/synthesis/symbolicexpr/abstractGroupTerm.go
  pkg/synthesis/symbolicexpr/allGroup.go
  pkg/synthesis/symbolicexpr/atomicGeneral.go
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/contradiction.go
  pkg/synthesis/symbolicexpr/externalIPTerm.go
  pkg/synthesis/symbolicexpr/groupAtomicTerm.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/internalIPTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/noGroup.go
  pkg/synthesis/symbolicexpr/symbolicexpr_GroupTag_test.go
  pkg/synthesis/symbolicexpr/symbolicexpr_IPBlock_test.go
  pkg/synthesis/symbolicexpr/tagTerm.go
  pkg/synthesis/symbolicexpr/tautology.go
Labels: size/XL

#363 350 internal ip to flow
  pkg/data/examples.go
  pkg/synthesis/symbolicexpr/externalIPTerm.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow_NoHint.txt
  pkg/synthesis/tests_expected_output/k8s_resources/Example1dExternalWithSegments_NoHint/policies.yaml
  pkg/synthesis/tests_expected_output/pre_process/Example1dExternalWithSegments_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllow_NoHint.txt
Labels: size/L

#368 Allow vm wo segment
  pkg/data/examples_generator.go
  pkg/data/json/ExampleInternalWithInterDenyAllow.json
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllow_NoHint.txt
Labels: size/XXL

#366 Abstract internal resources term
  pkg/synthesis/symbolicexpr/anyInternalResource.go
  pkg/synthesis/symbolicexpr/groupAtomicTerm.go
  pkg/synthesis/symbolicexpr/groupBasedInternalResource.go
  pkg/synthesis/symbolicexpr/groupTerm.go
  pkg/synthesis/symbolicexpr/internalIPTerm.go
  pkg/synthesis/symbolicexpr/model.go
  pkg/synthesis/symbolicexpr/tagTerm.go
Labels: size/L

#370 369 internal ip term abstract model bug
  pkg/data/examples.go
  pkg/data/json/ExampleInternalWithInterDenyAllow.json
  pkg/synthesis/symbolicexpr/conjunction.go
  pkg/synthesis/symbolicexpr/internalIPTerm.go
  pkg/synthesis/synthesis_test.go
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllowWithSegments.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllowWithSegments.txt
Labels: size/L

#376 cli fix
  pkg/cli/root.go
Labels: size/XS

#360 IP ranges reports
  internal/common/netset.go
  pkg/configuration/config.go
  pkg/configuration/parser.go
  pkg/configuration/topology.go
  pkg/configuration/topology/external_ip.go
  pkg/data/examples_generator.go
  pkg/data/json/ExampleHogwartsSimpler.json
  pkg/data/json/ExampleHogwartsSimplerNonSymInOut.json
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleHogwartsSimpler_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimplerNonSymInOutAdmin_AdminPoliciesEnabled/pods.yaml
  pkg/synthesis/tests_expected_output/k8s_resources/ExampleHogwartsSimpler_NoHint/pods.yaml
Labels: size/L

#383 382 exclude non relevant external
  pkg/synthesis/symbolicexpr/externalIPTerm.go
  pkg/synthesis/symbolicexpr/symbolicPath.go
  pkg/synthesis/tests_expected_output/abstract_models/Example1External_NoHint.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/abstract_models/ExampleInternalWithInterDenyAllowMixedSegments.txt
  pkg/synthesis/tests_expected_output/pre_process/Example1External_NoHint.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllow.txt
  pkg/synthesis/tests_expected_output/pre_process/ExampleInternalWithInterDenyAllowMixedSegments.txt
Labels: size/M
